#!/bin/zsh

if git rev-parse --verify HEAD >/dev/null 2>&1
then
        against=HEAD
else
        # Initial commit: diff against an empty tree object
        against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

export GIT_STAGE="$(git diff --cached --name-only --diff-filter=ACMR  $against | grep -E '\.(tsx|ts|js|jsx)$' | grep src)"

NB_FILE=$(echo $GIT_STAGE | wc -l | cut -d" " -f1)
if [  "$NB_FILE" !=  "0" ]; then

    echo TESTS
	npm run test

	RESULT=$?
	[ ${RESULT} -eq 0 ] || { echo -e "\e[0;31mTESTS FAILED \e[0m" && exit ${RESULT} }

    echo ESLINT
	echo ${GIT_STAGE} | xargs -n50 npm run checkPreCommit

	RESULT=$?
	[ ${RESULT} -eq 0 ] ||  { echo -e "\e[0;31mESLINT FAILED \e[0m" && exit ${RESULT} }
fi
